import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        bg:          'var(--bg)',
        'bg-soft':   'var(--bg-soft)',
        ink:         'var(--ink)',
        'ink-mute':  'var(--ink-mute)',
        line:        'var(--line)',
        'line-strong':'var(--line-strong)',
        fill:        'var(--fill)',
        'fill-2':    'var(--fill-2)',
        accent:      'var(--accent)',
      },
      fontFamily: {
        mono:    ['var(--font-mono)', 'IBM Plex Mono', 'monospace'],
        display: ['var(--font-display)', 'Cormorant Garamond', 'serif'],
        sans:    ['var(--font-sans)', 'Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        '10':  ['10px',  { lineHeight: '1.4' }],
        '11':  ['11px',  { lineHeight: '1.4' }],
        '12':  ['12px',  { lineHeight: '1.4' }],
        '13':  ['13px',  { lineHeight: '1.4' }],
        '14':  ['14px',  { lineHeight: '1.4' }],
        '18':  ['18px',  { lineHeight: '1.4' }],
        '20':  ['20px',  { lineHeight: '1.4' }],
        '22':  ['22px',  { lineHeight: '1.4' }],
        '24':  ['24px',  { lineHeight: '1.55' }],
        '28':  ['28px',  { lineHeight: '1.05' }],
        '30':  ['30px',  { lineHeight: '1.35' }],
        '32':  ['32px',  { lineHeight: '1.05' }],
        '36':  ['36px',  { lineHeight: '1' }],
        '48':  ['48px',  { lineHeight: '1' }],
        '64':  ['64px',  { lineHeight: '1' }],
      },
      letterSpacing: {
        '005': '0.05em',
        '01':  '0.1em',
        '012': '0.12em',
        '014': '0.14em',
        '015': '0.15em',
        '016': '0.16em',
        '018': '0.18em',
        '02':  '0.2em',
        tight: '-0.01em',
        tighter: '-0.02em',
      },
      lineHeight: {
        '09':  '0.9',
        '092': '0.92',
        '105': '1.05',
        '11':  '1.1',
        '135': '1.35',
        '145': '1.45',
        '155': '1.55',
        '16':  '1.6',
        '18':  '1.8',
      },
      gridTemplateColumns: {
        'nav':        'auto 1fr auto auto',
        'hero':       'auto 1fr',
        'about':      '1.4fr 1fr',
        'footer':     '1.5fr 1fr',
        'projects':   '1.7fr 1fr',
        'section-hdr':'120px 1fr auto',
        'work-row':   '80px 1fr auto',
        'contact':    '80px 1fr',
        'case-hero':  '1fr 1.4fr',
        '2-even':     '1fr 1fr',
        '3-even':     'repeat(3, 1fr)',
        '4-even':     'repeat(4, 1fr)',
        '5-even':     'repeat(5, 1fr)',
      },
      spacing: {
        '3.5': '14px',
        '4.5': '18px',
      },
      maxWidth: {
        '480': '480px',
        '520': '520px',
        '600': '600px',
        '720': '720px',
      },
      height: {
        '35':  '140px',
        '95':  '380px',
        '120': '480px',
        '145': '580px',
        '170': '680px',
      },
      minHeight: {
        '40':  '160px',
        '60':  '240px',
      },
      backdropBlur: {
        '12': '12px',
      },
    },
  },
  plugins: [],
}

export default config
